spring.application.name=projectbackend

spring.datasource.url=jdbc:mysql://localhost:3306/tienda_virtual?serverTimezone=UTC&useSSL=false
spring.datasource.username=usuario_proyecto
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ejecutar data.sql con JPA
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Swagger (springdoc)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
